SET TERM ^ ;

CREATE OR ALTER PACKAGE NANO$
AS
BEGIN

  FUNCTION set_locale(
    udr_locale VARCHAR(20) CHARACTER SET NONE NOT NULL
  ) RETURNS TY$NANO_BLANK;

  FUNCTION e_message RETURNS VARCHAR(512) CHARACTER SET UTF8;

END^

RECREATE PACKAGE BODY NANO$
AS
BEGIN

  FUNCTION set_locale(
    udr_locale VARCHAR(20) CHARACTER SET NONE NOT NULL
    ) RETURNS TY$NANO_BLANK
    EXTERNAL NAME 'nano!set_locale'
    ENGINE UDR;

  FUNCTION e_message RETURNS VARCHAR(512) CHARACTER SET UTF8
    EXTERNAL NAME 'nano!e_message'
    ENGINE UDR;

END^

SET TERM ; ^

/* Existing privileges on this package */

GRANT EXECUTE ON PACKAGE NANO$ TO SYSDBA;
