SET TERM ^ ;

CREATE OR ALTER PACKAGE NANO$RSLT
AS
BEGIN

  FUNCTION valid(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;

  FUNCTION release_(rslt TY$POINTER NOT NULL) RETURNS TY$POINTER;

  FUNCTION connection(rslt TY$POINTER NOT NULL) RETURNS TY$POINTER;

  FUNCTION rowset_size(rslt TY$POINTER NOT NULL) RETURNS INTEGER;
  FUNCTION affected_rows(rslt TY$POINTER NOT NULL) RETURNS INTEGER;
  FUNCTION has_affected_rows(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;
  FUNCTION rows_(rslt TY$POINTER NOT NULL) RETURNS INTEGER;
  FUNCTION columns(rslt TY$POINTER NOT NULL) RETURNS SMALLINT;

  ------------------------------------------------------------------------------

  FUNCTION first_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;
  FUNCTION last_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;
  FUNCTION next_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;
  FUNCTION prior_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;
  FUNCTION move(rslt TY$POINTER NOT NULL, row_ INTEGER NOT NULL) RETURNS BOOLEAN;
  FUNCTION skip_(rslt TY$POINTER NOT NULL, row_ INTEGER NOT NULL) RETURNS BOOLEAN;
  FUNCTION position_(rslt TY$POINTER NOT NULL) RETURNS INTEGER;
  FUNCTION at_end(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;

  ------------------------------------------------------------------------------

  FUNCTION unbind(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS TY$NANO_BLANK;

  FUNCTION is_null(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS BOOLEAN;

  FUNCTION is_bound(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS BOOLEAN;

  FUNCTION column_(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS SMALLINT;

  FUNCTION column_name(rslt TY$POINTER NOT NULL, index_ SMALLINT NOT NULL)
    RETURNS VARCHAR(63) CHARACTER SET UTF8;

  FUNCTION column_size(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER;

  FUNCTION column_decimal_digits(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER;

  FUNCTION column_datatype(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER;

  FUNCTION column_datatype_name(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS VARCHAR(63) CHARACTER SET UTF8;

  FUNCTION column_c_datatype(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER;

  FUNCTION next_result(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;

  ------------------------------------------------------------------------------

  FUNCTION has_data(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN;

END^

RECREATE PACKAGE BODY NANO$RSLT
AS
BEGIN

  FUNCTION valid(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$valid'
    ENGINE UDR;

  FUNCTION release_(rslt TY$POINTER NOT NULL) RETURNS TY$POINTER
    EXTERNAL NAME 'nano!rslt$release'
    ENGINE UDR;

  FUNCTION connection(rslt TY$POINTER NOT NULL) RETURNS TY$POINTER
    EXTERNAL NAME 'nano!rslt$connection'
    ENGINE UDR;

  FUNCTION rowset_size(rslt TY$POINTER NOT NULL) RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$rowset_size'
    ENGINE UDR;

  FUNCTION affected_rows(rslt TY$POINTER NOT NULL) RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$affected_rows'
    ENGINE UDR;

  FUNCTION has_affected_rows(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$has_affected_rows'
    ENGINE UDR;

  FUNCTION rows_(rslt TY$POINTER NOT NULL) RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$rows'
    ENGINE UDR;

  FUNCTION columns(rslt TY$POINTER NOT NULL) RETURNS SMALLINT
    EXTERNAL NAME 'nano!rslt$columns'
    ENGINE UDR;

  ------------------------------------------------------------------------------

  FUNCTION first_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$first'
    ENGINE UDR;

  FUNCTION last_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$last'
    ENGINE UDR;

  FUNCTION next_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$next'
    ENGINE UDR;

  FUNCTION prior_(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$prior'
    ENGINE UDR;

  FUNCTION move(rslt TY$POINTER NOT NULL, row_ INTEGER NOT NULL) RETURNS BOOLEAN
     EXTERNAL NAME 'nano!rslt$move'
     ENGINE UDR;

  FUNCTION skip_(rslt TY$POINTER NOT NULL, row_ INTEGER NOT NULL) RETURNS BOOLEAN
     EXTERNAL NAME 'nano!rslt$skip'
     ENGINE UDR;

  FUNCTION position_(rslt TY$POINTER NOT NULL) RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$position'
    ENGINE UDR;

  FUNCTION at_end(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$at_end'
    ENGINE UDR;

  ------------------------------------------------------------------------------

  FUNCTION unbind(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS TY$NANO_BLANK
    EXTERNAL NAME 'nano!rslt$unbind'
    ENGINE UDR;

  FUNCTION is_null(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$is_null'
    ENGINE UDR;

  FUNCTION is_bound(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$is_bound'
    ENGINE UDR;

  FUNCTION column_(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS SMALLINT
    EXTERNAL NAME 'nano!rslt$column'
    ENGINE UDR;

  FUNCTION column_name(rslt TY$POINTER NOT NULL, index_ SMALLINT NOT NULL)
    RETURNS VARCHAR(63) CHARACTER SET UTF8
    EXTERNAL NAME 'nano!rslt$column_name'
    ENGINE UDR;

  FUNCTION column_size(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$column_size'
    ENGINE UDR;

  FUNCTION column_decimal_digits(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$column_decimal_digits'
    ENGINE UDR;

  FUNCTION column_datatype(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$column_datatype'
    ENGINE UDR;

  FUNCTION column_datatype_name(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS VARCHAR(63) CHARACTER SET UTF8
    EXTERNAL NAME 'nano!rslt$column_datatype_name'
    ENGINE UDR;

  FUNCTION column_c_datatype(rslt TY$POINTER NOT NULL, column_ VARCHAR(63) CHARACTER SET UTF8 NOT NULL)
    RETURNS INTEGER
    EXTERNAL NAME 'nano!rslt$column_c_datatype'
    ENGINE UDR;

  FUNCTION next_result(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$next_result'
    ENGINE UDR;

  ------------------------------------------------------------------------------

  FUNCTION has_data(rslt TY$POINTER NOT NULL) RETURNS BOOLEAN
    EXTERNAL NAME 'nano!rslt$has_data'
    ENGINE UDR;

END^

SET TERM ; ^

/* Existing privileges on this package */

GRANT EXECUTE ON PACKAGE NANO$RSLT TO SYSDBA;
