CREATE OR ALTER PACKAGE NANO$TNX
AS
BEGIN
 
  FUNCTION transaction_(conn TY$POINTER NOT NULL) RETURNS TY$POINTER;

  FUNCTION dispose(tnx ty$pointer NOT NULL) RETURNS TY$POINTER;

  FUNCTION commit_(tnx TY$POINTER NOT NULL) RETURNS TY$NANO_BLANK;
  FUNCTION rollback_(tnx TY$POINTER NOT NULL) RETURNS TY$NANO_BLANK;

  FUNCTION connection(tnx TY$POINTER NOT NULL) RETURNS TY$POINTER;

END