SET TERM ^ ;

CREATE OR ALTER PACKAGE NANO$UDR
AS
BEGIN

  FUNCTION initialize(
      udr_locale VARCHAR(20) CHARACTER SET NONE DEFAULT 'cp1251'
    ) RETURNS TY$NANO_BLANK;

  FUNCTION set_locale(
    udr_locale VARCHAR(20) CHARACTER SET NONE NOT NULL
  ) RETURNS TY$NANO_BLANK;

  FUNCTION error_message RETURNS VARCHAR(512) CHARACTER SET UTF8;

  FUNCTION expunge RETURNS TY$NANO_BLANK;

END^

RECREATE PACKAGE BODY NANO$UDR
AS
BEGIN

  FUNCTION initialize(
      udr_locale VARCHAR(20) CHARACTER SET NONE
    ) RETURNS TY$NANO_BLANK
    EXTERNAL NAME 'nano!initialize'
    ENGINE UDR;

  FUNCTION set_locale(
      udr_locale VARCHAR(20) CHARACTER SET NONE NOT NULL
    ) RETURNS TY$NANO_BLANK
    EXTERNAL NAME 'nano!set_locale'
    ENGINE UDR;

  FUNCTION error_message RETURNS VARCHAR(512) CHARACTER SET UTF8
    EXTERNAL NAME 'nano!error_message'
    ENGINE UDR;

  FUNCTION expunge RETURNS TY$NANO_BLANK
    EXTERNAL NAME 'nano!expunge'
    ENGINE UDR;

END^

SET TERM ; ^

/* Existing privileges on this package */

GRANT EXECUTE ON PACKAGE NANO$UDR TO SYSDBA;
